package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Wednesday, 6 May, 2026 12:19:12 PM IST
*/

public interface CalculatorOperations 
{
  float add (float a, float b);
  float subtract (float a, float b);
  float multiply (float a, float b);
  float divide (float a, float b) throws CalculatorApp.DivisionByZero;
} // interface CalculatorOperations
